# Use the Alpine Linux base image
FROM alpine:latest

# Install Git
RUN apk --update add git

# Set the working directory
WORKDIR /app

# Set the default command to execute when the container starts
CMD ["sh"]
